name: 🐧 Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Compile
        run: deno compile --allow-net=www.fia.com,discordapp.com,discord.com --allow-read=./ ./index.ts

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: Binary
          path: ./FIADocsDeno
